parameters:
  ghn_session_redirect: ghn_redirect
  ghn_session_service_fee: ghn_service
#  production
#  ghn_endpoint: https://console.ghn.vn/api/v1/apiv3
#  Testing
  ghn_endpoint: https://apiv3-test.ghn.vn/api/v1/apiv3
  ghn_name_len: 50